"""add player season stats and insights

Revision ID: e4f867642d2e
Revises: 7b3ad3c81149
Create Date: 2026-08-30 15:20:50.959170
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f867642d2e'
down_revision: str | None = '7b3ad3c81149'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'kind', name='uq_player_insights_player_season_kind')
    )
    op.create_index(op.f('ix_player_insights_kind'), 'player_insights', ['kind'], unique=False)
    op.create_index(op.f('ix_player_insights_player_id'), 'player_insights', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_insights_season'), 'player_insights', ['season'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('rebounds', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('fg3_pct', sa.Float(), nullable=False),
    sa.Column('fg3a', sa.Float(), nullable=False),
    sa.Column('ts_pct', sa.Float(), nullable=False),
    sa.Column('usage_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season_stats_player_season')
    )
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season'), 'player_season_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_season_stats_team_id'), 'player_season_stats', ['team_id'], unique=False)
    op.add_column('players', sa.Column('nba_player_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('roster_season', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_nba_player_id'), 'players', ['nba_player_id'], unique=True)
    op.create_index(op.f('ix_players_roster_season'), 'players', ['roster_season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_roster_season'), table_name='players')
    op.drop_index(op.f('ix_players_nba_player_id'), table_name='players')
    op.drop_column('players', 'roster_season')
    op.drop_column('players', 'nba_player_id')
    op.drop_index(op.f('ix_player_season_stats_team_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_season'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_player_insights_season'), table_name='player_insights')
    op.drop_index(op.f('ix_player_insights_player_id'), table_name='player_insights')
    op.drop_index(op.f('ix_player_insights_kind'), table_name='player_insights')
    op.drop_table('player_insights')
    # ### end Alembic commands ###
