"""initial schema

Revision ID: a3ceba4cf6cd
Revises: 
Create Date: 2026-08-06 13:22:36.556627
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ceba4cf6cd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('conference', sa.String(length=16), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('postseason', sa.Boolean(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('visitor_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('visitor_team_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visitor_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_visitor_team_id'), 'games', ['visitor_team_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('height', sa.String(length=8), nullable=True),
    sa.Column('weight', sa.String(length=8), nullable=True),
    sa.Column('jersey_number', sa.String(length=8), nullable=True),
    sa.Column('college', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('conference', sa.String(length=16), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('home_record', sa.String(length=16), nullable=True),
    sa.Column('road_record', sa.String(length=16), nullable=True),
    sa.Column('streak', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', name='uq_standings_season_team')
    )
    op.create_index(op.f('ix_standings_season'), 'standings', ['season'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_injuries_status'), 'injuries', ['status'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('predicted_home_win_prob', sa.Float(), nullable=False),
    sa.Column('predicted_home_win', sa.Boolean(), nullable=False),
    sa.Column('actual_home_win', sa.Boolean(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'model_version', name='uq_model_predictions_game_version')
    )
    op.create_index(op.f('ix_model_predictions_game_id'), 'model_predictions', ['game_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_version'), 'model_predictions', ['model_version'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(length=8), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_stats_player_game')
    )
    op.create_index(op.f('ix_player_stats_game_id'), 'player_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_season'), 'player_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points_for', sa.Integer(), nullable=False),
    sa.Column('points_against', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_team_stats_game_team')
    )
    op.create_index(op.f('ix_team_stats_game_id'), 'team_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_stats_season'), 'team_stats', ['season'], unique=False)
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_season'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_game_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_season'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_game_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_model_predictions_model_version'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_game_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_injuries_status'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_season'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_visitor_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
