"""add season_projections

Revision ID: 7b3ad3c81149
Revises: a3ceba4cf6cd
Create Date: 2026-08-27 14:05:26.985772
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3ad3c81149'
down_revision: str | None = 'a3ceba4cf6cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('proj_wins', sa.Float(), nullable=False),
    sa.Column('proj_losses', sa.Float(), nullable=False),
    sa.Column('wins_p10', sa.Float(), nullable=False),
    sa.Column('wins_p50', sa.Float(), nullable=False),
    sa.Column('wins_p90', sa.Float(), nullable=False),
    sa.Column('make_playoffs_pct', sa.Float(), nullable=False),
    sa.Column('win_conference_pct', sa.Float(), nullable=False),
    sa.Column('win_title_pct', sa.Float(), nullable=False),
    sa.Column('avg_seed', sa.Float(), nullable=False),
    sa.Column('simulations', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', 'model_version', name='uq_season_projections_season_team_version')
    )
    op.create_index(op.f('ix_season_projections_model_version'), 'season_projections', ['model_version'], unique=False)
    op.create_index(op.f('ix_season_projections_season'), 'season_projections', ['season'], unique=False)
    op.create_index(op.f('ix_season_projections_team_id'), 'season_projections', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_projections_team_id'), table_name='season_projections')
    op.drop_index(op.f('ix_season_projections_season'), table_name='season_projections')
    op.drop_index(op.f('ix_season_projections_model_version'), table_name='season_projections')
    op.drop_table('season_projections')
    # ### end Alembic commands ###
